# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17biRFt7WUTIKi97kiE1dCdJb3afq0hg-
"""

import streamlit as st

st.title("My Gaming Chat App is Working!")
st.write("If you can see this, the UI is rendering.")

import streamlit as st
from transformers import pipeline
from huggingface_hub import InferenceClient
import os

# ==========================================
# PAGE CONFIGURATION & UI SETUP
# ==========================================
st.set_page_config(page_title="Riot Games Chat Purifier", page_icon="🎮", layout="centered")
st.title("🎮 The Chat Purifier: Toxic to Humorous")
st.markdown("**Target Company:** Riot Games | **Objective:** Neutralize toxic chat with humor.")

# ==========================================
# PIPELINE 1: TOXICITY DETECTION (Fine-tuned)
# ==========================================
@st.cache_resource
def load_toxicity_model():
    """
    Loads the fine-tuned toxicity classification model.
    Cached to prevent reloading on every user interaction.
    """
    model_id = "RachelHu123/toxic-comment-finetuned"
    return pipeline("text-classification", model=model_id, truncation=True)

toxicity_classifier = load_toxicity_model()

# ==========================================
# PIPELINE 2: HUMOROUS REWRITING (LLM API)
# ==========================================
def rewrite_toxic_chat(toxic_text):
    """
    Uses Hugging Face Inference API to rewrite toxic text.
    Requires HF_TOKEN in Streamlit Secrets.
    """
    # Initialize client with a fast, instruction-tuned LLM
    hf_token = st.secrets.get("HF_TOKEN", os.getenv("HF_TOKEN"))
    client = InferenceClient(model="mistralai/Mistral-7B-Instruct-v0.2", token=hf_token)

    prompt = (
        "You are an elegant, polite, and slightly sarcastic British butler moderating a video game chat. "
        f"Rewrite the following toxic gamer message into a highly polite, poetic, and humorous compliment. "
        f"Do not include any explanations, just output the rewritten message.\n\n"
        f"Toxic message: '{toxic_text}'\n\n"
        f"Rewritten message:"
    )

    try:
        response = client.text_generation(prompt, max_new_tokens=60, temperature=0.7)
        return response.strip()
    except Exception as e:
        return "Ah, it seems the server goblins are acting up. Please try again later."

# ==========================================
# MAIN APP LOGIC
# ==========================================
st.subheader("💬 Live Game Chat Simulation")
user_input = st.text_input("Enter a chat message:", placeholder="e.g., You play like an absolute idiot!")

if st.button("Send Message"):
    if user_input.strip():
        with st.spinner("Analyzing message..."):
            # 1. Run Pipeline 1 (Detection)
            prediction = toxicity_classifier(user_input)[0]
            label = prediction['label']

            # Note: Depending on your fine-tuning, the label might be 'LABEL_1' or '1' for toxic.
            is_toxic = label in ['LABEL_1', '1', 'TOXIC']

            if is_toxic:
                st.warning("⚠️ Toxic behavior detected! Purifying...")
                # 2. Run Pipeline 2 (Transformation)
                purified_message = rewrite_toxic_chat(user_input)

                st.success("✨ Message Purified & Broadcasted:")
                st.info(f"🗣️ **Player:** {purified_message}")
            else:
                st.success("✅ Message is clean. Broadcasted as-is:")
                st.info(f"🗣️ **Player:** {user_input}")
    else:
        st.error("Please enter a message first.")
